config/routes.rb
Rails.application.routes.draw do

  get '/users/:user_id/sales', to: 'sales#index_by_user', as: 'user_sales'
  get '/products/:product_id/sales', to: 'sales#index_by_product', as: 'product_sales'

  resources :products do
    resources :prices
    resources :sales
  end 

  resources :sales 

  devise_for :users

  resources :users, only: [:show]

  root 'products#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :product
  
  validates :price, presence: true
  validates :price, numericality: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :intersection_check
  
  def intersection_check
    errors.add(:start_date, 'Intersection of price') if Product.find(product_id).prices.where("start_date between ? and ? or end_date between ? and ?", start_date, end_date, start_date,  end_date).exists?

  end

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :prices
  has_many :sales
  
  def current_price
    if self.prices.where('start_date < ? and end_date > ?', Time.now, Time.now).exists?
      self.prices.where('start_date < ? and end_date > ?', Time.now, Time.now).first.price
    else
      nil
    end
  end
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :product_id, presence: true
  validates :quantity, presence: true
  validates :quantity, numericality: {only_integer: true, greater_than: 0}
  validates :date,  presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sales
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :authenticate_user!
  
  before_action :set_product
  before_action :set_price, only: [:show, :edit, :update, :destroy]
  
  def new
    @price = @product.prices.build
  end
  
  def create 
    @price = @product.prices.build(price_params)
    if @price.save
      flash[:notice] = t('notices.price.create')
      redirect_to [@product, @price]
    else
      flash[:alert] = t('alerts.price.create')
      render "new"
    end 
  end

  def index
    @prices = @product.prices
  end
  
  def show
    
  end

  private
  def set_product
    @product = Product.find(params[:product_id])
  end
  
  def set_price
    @price = @product.prices.find(params[:id])
  end
  
  def price_params
    params.require(:price).permit(:price, :start_date, :end_date)
  end  
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: t('notices.product.destroy.') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!
  
  before_action :set_product
  
  def new
    fill_products
    if @product.nil?
      @sale = Sale.new
    else 
      @sale = @product.sales.build
    end 
  end

  def index_by_user
    @user = User.find(params[:user_id])
    @sales = @user.sales.includes(:product)
  end

  def index_by_product
    @product = Product.find(params[:product_id])
    @sales = @product.sales.includes(:user)
  end
  
  def create
    fill_products
    if @product.nil?
      @sale = Sale.new(sale_params)
    else 
      @sale = @product.sales.build(sale_params)
    end 
    @sale.user = current_user
    if @sale.save
      flash[:notice] = t('notices.sale.create')
      if @product.nil? 
        redirect_to root_path
      else
        redirect_to @product
      end
    else
      flash[:alert] = t('alerts.sale.create')
      render "new"
    end
  end
  
private
  def set_product
    if params[:product_id].blank?
      @product = nil
    else
      @product = Product.find(params[:product_id])
    end
  end  
  
  def fill_products
    @products = Product.all
  end
  
  def sale_params
    params.require(:sale).permit(:quantity, :date, :product_id)  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  before_action :set_user

  def show
  end

  def set_user
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def strip_locale_url
    locale=I18n.locale
    request.original_url.sub(/locale=[a-zA-Z]{2}/,'')
  end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content =>  "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}/
    %title Project Motiv
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = render partial: 'shared/navigation'
      - if notice
        .alert.alert-success.alert-dismissible= notice
      - if alert
        .alert.alert-danger.alert-dismissible= alert
      = yield

app/views/prices/_form.html.haml
= form_for [@product, @price] do |f|
  - if @price.errors.any?
    #error_explanation
      %h2= "#{pluralize(@price.errors.count, "error")} prohibited this price from being saved:"
      %ul
        - @price.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :price
    = f.text_field :price
  .form-group
    = f.label :start_date
    = f.date_field :start_date
  .form-group
    = f.label :end_date
    = f.date_field :end_date
  .form-group
    = f.submit 'Assign', class: 'btn btn-default'

app/views/prices/_price.html.haml
= form_for [@product, @price] do |f|
  - if @price.errors.any?
    #error_explanation
      %h2= "#{pluralize(@price.errors.count, "error")} prohibited this price from being saved:"
      %ul
        - @price.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :price
    = f.text_field :price
  .form-group
    = f.label :start_date
    = f.date_field :start_date
  .form-group
    = f.label :end_date
    = f.date_field :end_date
  .form-group
    = f.submit t('btn.assign'), class: 'btn btn-default'

app/views/prices/index.html.haml
%h1= t('.title')

%div
  %table.table
    %thead
      %tr
        %th= Price.human_attribute_name(:start_date)
        %th= Price.human_attribute_name(:end_date)
        %th= Price.human_attribute_name(:price)
    %tbody
      - @prices.each do |p|
        %tr
          %td= l(p.start_date)
          %td= l(p.end_date)
          %td= p.price

%div
  = link_to t('btn.back'), product_path(@product)

app/views/prices/new.html.haml
%h1= t('.title')

= render @price

= link_to t('btn.back'), @product

app/views/prices/show.html.haml
%div
  = label :product, :price
  = @price.price

= link_to 'Back', @product

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name
  .form-group
    = f.submit t('btn.save'), class: 'btn btn-default'

app/views/products/edit.html.haml
%h1= t('.title')

= render 'form'

= link_to t('btn.show'), @product
\|
= link_to t('btn.back'), products_path

app/views/products/index.html.haml
%h1= t('.title')

%table.table
  %thead
    %tr
      %th= Product.human_attribute_name(:name)
      %th= t(:column_actions)

  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.name, product
        %td
          = link_to t('btn.show'), product, class: 'btn btn-default btn-xs'
          = link_to t('btn.edit'), edit_product_path(product), class: 'btn btn-default btn-xs'
          = link_to t('btn.destroy'), product, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-default btn-xs'

%br

= link_to t('.new_product'), new_product_path, class: 'btn btn-default'
= link_to t('.new_sale'), new_sale_path, class: 'btn btn-default'

app/views/products/new.html.haml
%h1= t('.title')

= render 'form'

= link_to t('btn.back'), products_path

app/views/products/show.html.haml
%h1= t('.title')
%div
  = label(:product, :name)
  = @product.name

  = label(:product, :current_price_is)
  = @product.current_price ? @product.current_price : "not defined" 

%div
  = link_to t('btn.sell'), new_product_sale_path(@product)
  = link_to t('.assign_price'), new_product_price_path(@product)
  = link_to t('.sales'), product_sales_path(@product)
  = link_to t('.prices'), product_prices_path(@product)
  = link_to t('btn.edit'), edit_product_path(@product)
  = link_to t('btn.back'), products_path

app/views/sales/_form2.html.haml
= form_for @sale do |f|
  - if @sale.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sale.errors.count, "error")} prohibited this sale from being saved:"
      %ul
        - @sale.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :product
    = f.collection_select :product_id, @products, :id, :name, prompt: 'Select product'
  .form-group
    = f.label :quantity
    = f.text_field :quantity
  .form-group
    = f.label :date
    = f.text_field :date
  .form-group
    = f.submit 'Sell'

app/views/sales/_sale.html.haml
= form_for @sale do |f|
  - if @sale.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sale.errors.count, "error")} prohibited this sale from being saved:"
      %ul
        - @sale.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :product
    = f.collection_select :product_id, @products, :id, :name, prompt: t('.select_product')
  .form-group
    = f.label :quantity
    = f.text_field :quantity
  .form-group
    = f.label :date
    = f.date_field :date
  .form-group
    = f.submit t('btn.sell'), class: 'btn btn-default'

app/views/sales/index_by_product.html.haml
%h1= t('sales.index.title')

%div
  %table.table
    %thead
      %tr
        %th= Sale.human_attribute_name(:date)
        %th= Sale.human_attribute_name(:quantity)
        %th= User.model_name.human
    %tbody
      - @sales.each do |s|
        %tr
          %td= l(s.date)
          %td= s.quantity
          %td= s.user.email
%div
  = link_to t('btn.back'), product_path(@product)

app/views/sales/index_by_user.html.haml
%h1= t('sales.index.title')

%div
  %table.table
    %thead
      %tr
        %th= Sale.human_attribute_name(:date)
        %th= Sale.human_attribute_name(:quantity)
        %th= Product.model_name.human
    %tbody
      - @sales.each do |s|
        %tr
          %td= l(s.date)
          %td= s.quantity
          %td= s.product.name
%div
  = link_to t('btn.back'), user_path(@user)

app/views/sales/new.html.haml
%h1= t('.title')

=render @sale

= link_to t('btn.back'), @product||root_path

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      = link_to 'Project Motiv', root_path, class: 'navbar-brand' 
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li
          = link_to current_user.email, user_path(current_user)
        %li
          = form_tag destroy_user_session_path, method: :delete, class: 'navbar-form' do
            = submit_tag t('btn.sign_out'), class: 'btn btn-default'
      - else
        %li
          = form_for @user, url: user_session_path, html: {class: 'navbar-form navbar-right'} do |f|
            .form-group
              = f.label :email, class: 'sr-only'
              = f.email_field :email, class: 'form-control', placeholder: t('activerecord.attributes.user.email')
            .form-group
              = f.label :password, class: 'sr-only'
              = f.password_field :password, class: 'form-control', placeholder: t('activerecord.attributes.user.password') 
            = submit_tag t('btn.sign_in'), class: 'btn btn-default'
      %li
        - if I18n.locale == :en
          = link_to 'Русский', locale: :ru
        - else
          = link_to 'English', locale: :en

app/views/users/show.html.haml
%h1= t('.title')

%div
  = label :user, :email
  = @user.email
%div
  = link_to t('.my_sales'), user_sales_path(@user)